FirstSapling: true
LavaProtect: true
PotionEffectKeeper: true
HungerKeeper: true
RailWay: true
IronElevator: true
SitDownAnywhere: true
PlayerHeadDrop: true
SlimeChunkCommand: true
ElderGuardianSpawner: true
ShulkerRespawn: true
MoreRecipe: true