name: SkydomIslandManager
version: ${version}
main: org.skydom.chosen.server.skydomislandmanager.SkydomIslandManager
api-version: 1.20.1
folia-supported: true
authors: [Chosen_1st]
commands:
  Slime:
    usage: /Slime
    description: Look The Slime Chunk
    permission: SkydomIslandManager.slime
    permission-message: You do not have permission.
    default: op
  Tips:
    usage: /Tips
    description: Look Tips
  Menu:
    usage: /Menu
    description: Open Menu