name: SkydomIslandManager
version: '${project.version}'
main: tk.chosen.skyblock.SkydomIslandManager
api-version: 1.18
authors: [Chosen, SkydomAdminGroup]
commands:
  Slime:
    usage: /Slime
    description: Look The Slime Chunk
    permission: SkydomIslandManager.slime
    permission-message: You do not have permission.
    default: op