name: SkydomIslandManager
version: '${project.version}'
main: org.skydom.chosen.skyblock.SkydomIslandManager
api-version: 1.19
authors: [Chosen, SkydomAdminGroup]
commands:
  Slime:
    usage: /Slime
    description: Look The Slime Chunk
    permission: SkydomIslandManager.slime
    permission-message: You do not have permission.
    default: op
  Tips:
    usage: /Tips
  Menu:
    usage: /Menu